spring.application.name=Student_Mgt_API_with_Global_Exception_Handling

server.port=4554

spring.datasource.url=jdbc:mysql://localhost:3306/StudentApiWithExceptionHandling
spring.datasource.username=root
spring.datasource.password=Prashant@1572

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true